### ISSUE TITLE
Improve Mask Results

### ISSUE THREAD

**Issue by user074** [ByungKwanLee/Full-Segment-Anything#1]
First great work to batch process images!
Is there anyway to improve the generated mask results? Some of the mask I have does not look so good with my images as what I got from SAM. Maybe I am doing something wrong?
<img width="448" alt="Screenshot 2023-11-20 at 1 34 41 AM" src="https://github.com/ByungKwanLee/Full-Segment-Anything/assets/25289138/cd92dd1b-1b59-4df2-b1fe-9396e0f7b20d">
<img width="446" alt="Screenshot 2023-11-20 at 1 34 52 AM" src="https://github.com/ByungKwanLee/Full-Segment-Anything/assets/25289138/3906ff4a-1828-4afa-af88-7d6684c5f158">

And this is from SAM Automatic Mask Generator:

<img width="429" alt="Screenshot 2023-11-20 at 1 35 01 AM" src="https://github.com/ByungKwanLee/Full-Segment-Anything/assets/25289138/a104b324-dc4c-4e0b-a518-fe8ffec1c262">

**Comment by ByungKwanLee** [comment]
I would like to ask: (1) is your original image size is 256? (2) original SAM input is fixed to 1024 but how to propagate in SAM code with automatic mask generator?

**Comment by user074** [comment]
Yeah they are. I use the SamAutomaticMaskGenerator and it is able to accept different sizes and I experimented on that. It can accept many non-standard sizes.

**Comment by user074** [comment]
Wait I think I find the issue. The way to normalize and preprocess the image really have a lot of affects on the outcome.

**Comment by ByungKwanLee** [comment]
is the problem you experienced due to my code issue?

**Comment by user074** [comment]
No I think it is the SAM model part. Not sure how they normalize their images but it gives better results with their pipeline. Great work by the way! But I probably will use FastSAM since it is much faster than SAM

**Comment by Ashutosh1995** [comment]
@user074 were you able to send a custom image size and train the SAM model. What changes did you do? Can you please explain in depth?
