### ISSUE TITLE
Questions regarding Automatic Mask generator

### ISSUE THREAD

**Issue by sethuramanio** [ByungKwanLee/Full-Segment-Anything#6]
Hi , 

Thanks for the code. I tried running it and the output seems good. I guess the current batch inference works for full grid prompting using sam.predict method which in your case is sam.individual_forward(). Does the same batch processing exists for sam automatic mask generator function? because we would like to get the masks along with the bounding box coordinates for the corresponding masks? or is there a way to get the same using the current sam.individual_forward(). 

Thank you so much.

**Comment by ByungKwanLee** [comment]
Sorry for the late reply due to paper submission :) In the current version, there is no way of inputting bounding box coordinates with full batch. However, in this case, I think proessing one by one in each image is more intuitive and efficient way.

**Comment by sethuramanio** [comment]
Hi, thanks for the reply. No problem. Got it. Thanks
